<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="RootElement" nsURI="http:///RootElement.ecore" nsPrefix="RootElement">
  <eClassifiers xsi:type="ecore:EClass" name="Resource">
    <eStructuralFeatures xsi:type="ecore:EReference" name="base_Class" ordered="false"
        lowerBound="1" eType="ecore:EClass ../org.eclipse.uml2.uml/model/UML.ecore#//Class"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Layout">
    <eStructuralFeatures xsi:type="ecore:EReference" name="base_Class" ordered="false"
        lowerBound="1" eType="ecore:EClass ../org.eclipse.uml2.uml/model/UML.ecore#//Class"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SignalEmitter" eSuperTypes="#//Resource"/>
  <eClassifiers xsi:type="ecore:EClass" name="Agent" eSuperTypes="#//Resource">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" ordered="false" lowerBound="1"
        eType="ecore:EDataType ../org.eclipse.uml2.types/model/Types.ecore#//String"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="state" ordered="false"
        lowerBound="1" eType="ecore:EDataType ../org.eclipse.uml2.types/model/Types.ecore#//Boolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Object" eSuperTypes="#//Resource"/>
  <eClassifiers xsi:type="ecore:EClass" name="Operator" eSuperTypes="#//Agent"/>
  <eClassifiers xsi:type="ecore:EClass" name="MobileDevice" eSuperTypes="#//Agent"/>
  <eClassifiers xsi:type="ecore:EClass" name="EndEffector" eSuperTypes="#//Agent"/>
  <eClassifiers xsi:type="ecore:EClass" name="Gripper" eSuperTypes="#//EndEffector"/>
  <eClassifiers xsi:type="ecore:EClass" name="Screwdriver" eSuperTypes="#//EndEffector"/>
  <eClassifiers xsi:type="ecore:EClass" name="Joint"/>
</ecore:EPackage>
